Documentation for using HTML in notes
srid/neuron pull request #442
Opened 2020-10-19 09:48 UTC by flyinggrizzly

This PR adds documentation for using HTML in Neuron markdown.

Because Neuron scans notes for links before passing them to the MD parser, and because Neuron still supports `<note-name>` link syntax, it treats simple HTML elements as notes, which result in missing/unknown note warnings.

The documentation added covers two solutions:

1. Using Commonmark raw-attribute syntax as noted in https://github.com/srid/neuron/issues/437#issuecomment-710698849
2. Adding an HTML attribute to the element

Adds documentation for #437

---

## Consideration

I discovered the option of adding HTML attrs when I was wondering why an `iframe` worked in a note without the raw-attribute syntax, but `video` didn't. It has worked for every basic HTML element I've tried to use it for without issue.

The upside, is that the Markdown is more idiomatic, and less tied to Commonmark. The downside is the proliferation of classes/attributes. However, the attribute only appears to be required on the outmost HTML element of a block.

2020-10-19 20:07 UTC, srid requested changes
Awesome, thanks for the elaborate documentation on the topic! Just a few things to address before the merge.

2020-10-19 20:07 UTC, srid commented on guide/using-html-in-markdown.md
> +Usually, Markdown supports raw HTML inline as valid Markdown syntax.
Since neuron uses `commonmark` (which does support raw HTML), you should link to the spec: https://spec.commonmark.org/0.28/#raw-html

2020-10-19 20:07 UTC, srid commented on guide/using-html-in-markdown.md
> +### Using raw-attributes to insert HTML
Better to title it as "Using fenced code blocks"

2020-10-19 20:07 UTC, srid commented on guide/using-html-in-markdown.md
> +### Using HTML attributes to cause Neuron to recognize HTML elements
Better: "Using HTML attributes"

2020-10-19 20:07 UTC, srid commented on guide/using-html-in-markdown.md
> +If an HTML attribute is added to an element, Neuron ignores it while generating the link heterarchy and passes it unchanged to the Markdown parser.
Replace with: "If the top-level HTML element has one or more attributes, neuron will never parse it as a link".

2020-10-19 20:07 UTC, srid commented on guide/using-html-in-markdown.md
> +<video class="force-html"><source src='static/video.mp4 /></video>
I suppose you can instead add `id=some-video`, which is probably better (to avoid using some accidental CSS class).

2020-10-19 20:09 UTC, srid commented on guide/markdown.md
> +* [[[using-html-in-markdown]]]
And should also be added to the list, at the bottom (not front).

2020-10-20 10:36 UTC, flyinggrizzly commented
I've added 3 commits that should resolve the requested changes. Let me know if you'd like me to rebase this down to one or two commits before merging!

2020-10-26 17:55 UTC, merged

2020-10-26 17:55 UTC, srid commented
Thanks! This had slipped out of my radar accidentally; merged now.

2020-10-27 10:15 UTC, flyinggrizzly commented
No worries--I'm glad I could help!